[package]
name = "impl_inheritance"
version = "0.0.2"
authors = ["macpp"]
edition = "2018"
license="MIT"
description = "experimental & work in progress"

[dependencies]
impl_inheritance_macros = {path="impl_inheritance_macros"}
#impl_inheritance_macros = "0.0.2"