[lib]
proc-macro=true
[package]
name = "impl_inheritance_macros"
version = "0.0.2"
authors = ["macpp"]
edition = "2018"
license="MIT"
description = "experimental & work in progress"

[dependencies]
quote = "0.6"
proc-macro2 = {version= "0.4"}
syn = {version = "0.15", features = ["full"]}